generic-service:
  nameOverride: hmpps-electronic-monitoring-data-platform-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-electronic-monitoring-data-platform-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-electronic-monitoring-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-electronic-monitoring-data-platform-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    rds-postgresql:
      DATABASE_URL: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-electronic-monitoring-data-platform-api
