version: "3"
services:
  hmpps-electronic-monitoring-data-platform-api:
    build:
      context: .
#    network_mode: "host"
    container_name: hmpps-electronic-monitoring-data-platform-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
#    networks:
#      - ktor-network
#    depends_on:
#      - database

  database:
    image: postgres:latest
    volumes:
     - ./tmp/db:/var/lib/postgresql/data
    container_name: ktor-db
#    environment:
#      POSTGRES_DB: ktor
#      POSTGRES_HOST_AUTH_METHOD: trust
#    ports:
#      - "54333:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 1s
    environment:
      - POSTGRES_DB = ktor
      - POSTGRES_USER = root
      - POSTGRES_PASSWORD = root
    ports:
      - 5432:5432
    expose:
      - 5432
#    networks:
#      - ktor-network


networks:
  hmpps:
  ktor-network:
    driver: bridge
