version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=testcontainers
      - POSTGRES_USER=1234
      - POSTGRES_DB=testcontainers_demo
    ports:
      - "5430:5430"