#server:
#  shutdown: immediate

#management.endpoint:
#  health.cache.time-to-live: 0
#  info.cache.time-to-live: 0

api:
  base:
    url:
      oauth: https://sign-in-dev.hmpps.service.justice.gov.uk/auth